### ISSUE TITLE
Where can I find The class DynamicModel and AttributeModel

### ISSUE THREAD

**Issue by Alvinsjq** [gephi/gephi-toolkit#25] opened 2017-12-29 03:16 UTC
I am trying to run the toolkit-demo program and wanna implement a dynamic graph.

So, I have found the website How to execute a metric over time and learn to run it.
However, I found that is different from the code in the file DynamicMetric in toolkit-demo. And I cannot find the class **DynamicModel** and **AttributeModel**.
**Are these classes not in the toolkit?**

Thank you for your help!

**Comment by eduramiba** [comment] 2017-12-31 12:15
Duplicate of https://github.com/gephi/gephi/issues/1884

**Closed by eduramiba** 2017-12-31 12:15 UTC
